services:
  dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "8000:8000"
    environment:
      CDN_BASE_URL: ""
    command: >
      sh -lc '
        npm ci &&
        printf "window.APP_CONFIG={CDN_BASE_URL:\"%s\"};" "$CDN_BASE_URL" > public/js/config.js &&
        npm run dev
      '

volumes:
  node_modules:
