services:
  web:
    image: registry.digitalocean.com/${DOCR_NAME}/mortrem-epk:${IMAGE_TAG}
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: ${DOMAIN}
      CDN_BASE_URL: ${CDN_BASE_URL}
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped

volumes:
  caddy-data:
  caddy-config:
