services:
  web:
    image: registry.digitalocean.com/${DOCR_NAME}/mortrem-epk:${IMAGE_TAG}
    ports:
      - "80:80"
      - "443:443"
    environment:
      CDN_BASE_URL: ${CDN_BASE_URL}
      DOMAIN: "epk.mortrem.band"
      EMAIL: "mortremofficial@gmail.com"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
