name: Deploy EPK to DigitalOcean (Nginx)

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

env:
  REGISTRY: registry.digitalocean.com/${{ secrets.DOCR_NAME }}
  IMAGE: registry.digitalocean.com/${{ secrets.DOCR_NAME }}/mortrem-epk

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.meta.outputs.IMAGE_TAG }}
    steps:
      - uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Login to DO Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Build and push image
        id: meta
        run: |
          TAG=${GITHUB_SHA::7}
          docker build -t $IMAGE:$TAG -t $IMAGE:latest .
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest
          echo "IMAGE_TAG=$TAG" >> $GITHUB_OUTPUT

  sync-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Upload ./assets to DigitalOcean Spaces (CDN origin)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET }}
          SPACES_REGION: ${{ secrets.SPACES_REGION }}
          SPACES_BUCKET: ${{ secrets.SPACES_BUCKET }}
        run: |
          set -euo pipefail
          ENDPOINT="https://${SPACES_REGION}.digitaloceanspaces.com"
          # Sync assets folder to s3://<bucket>/assets (public)
          aws s3 sync ./assets "s3://${SPACES_BUCKET}/assets" \
            --endpoint-url "$ENDPOINT" \
            --acl public-read \
            --delete \
            --no-progress
          # Note: object Cache-Control is optional; your CDN TTL can handle caching.
          # If you want aggressive browser caching, you can set per-file headers later.

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH & deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}   # 'root' if you SSH as root
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -euo pipefail

            # Install Docker if missing
            if ! command -v docker >/dev/null; then
            curl -fsSL https://get.docker.com | sh
            fi

            mkdir -p /srv/mortrem-epk
            cd /srv/mortrem-epk

            # Log in to DOCR so the droplet can pull the private image
            echo "${{ secrets.DO_API_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin || true


            # Write compose with literal values (no env expansion needed)
            cat > docker-compose.prod.yml <<'YAML'
            services:
              web:
                image: registry.digitalocean.com/${{ secrets.DOCR_NAME }}/mortrem-epk:${{ needs.build-and-push.outputs.IMAGE_TAG }}
                ports:
                  - "80:80"
                environment:
                  - CDN_BASE_URL=${{ secrets.CDN_BASE_URL }}
                restart: unless-stopped
            YAML

            # Write .env so docker compose picks it up automatically
            cat > .env <<EOF
            DOCR_NAME=${{ secrets.DOCR_NAME }}
            IMAGE_TAG=${{ needs.build-and-push.outputs.IMAGE_TAG }}
            CDN_BASE_URL=${{ secrets.CDN_BASE_URL }}
            EOF

            # Open firewall for HTTP if UFW is in use
            if command -v ufw >/dev/null; then
              sudo ufw allow 80/tcp || true
            fi

            sudo docker compose -f docker-compose.prod.yml up -d
